name: Simple IF Example

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello"

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        run: |
          echo "Deploying production"
          exit 1

      - name: Final Step
        run: echo "Workflow continues..."
     