name: Simple IF Example

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello"

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Deploying production"


jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - name: say Hi
        if: github.event_name == 'push'
        run: echo "say Hii!!"          