name: Simple IF Example

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello"

      - name: Run only on master branch
        if: github.ref == 'refs/heads/master'
        run: echo "This is the master branch"